name: Kubernetes CI/CD Pipeline

on:
  push:
    branches: [main] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Minikube (with k8s cluster)
      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest

      # Build Docker image inside Minikube
      - name: Build Docker image in Minikube
        run: minikube image build -t pipeline-demo:latest .

      # Deploy Redis to Minikube
      - name: Deploy Redis
        run: |
          kubectl apply -f redis-deployment.yaml
          kubectl apply -f redis-service.yaml
      # Deploy Flask app & service to Minikube
      - name: Deploy Flask app
        run: |
          kubectl apply -f deployment-def.yaml
          kubectl apply -f service-def.yaml

